# yaml-language-server: $schema=https://www.schemastore.org/yamllint.json
extends: default
rules:
  line-length:
    max: 220
    level: error
  document-start: disable
  truthy: disable
  comments:
    min-spaces-from-content: 1
